version: '3.7'

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/index.js
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: simple-express-ts
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev